import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useI18n } from '../hooks/useI18n';
import { SpeechBubble } from '../components/SpeechBubble';
import { Button } from '../components/Button';
import { Card } from '../components/Card';
import { characterEmojis } from 'content';
export default function Welcome() {
    const { t, direction, locale, setLocale } = useI18n();
    return (_jsx("div", { className: "min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4", dir: direction, children: _jsxs("div", { className: "max-w-4xl mx-auto text-center", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6 }, className: "mb-8", children: [_jsx("div", { className: "text-8xl mb-4", role: "img", "aria-label": "Detective Luna", children: characterEmojis.luna }), _jsx("h1", { className: "text-5xl md:text-6xl font-bold text-indigo-700 mb-4", children: t('welcome.title') })] }), _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: 0.2 }, className: "mb-6", children: [_jsx("p", { className: "text-xl md:text-2xl text-gray-600 mb-4", children: t('welcome.subtitle') }), _jsx("p", { className: "text-lg text-gray-500", children: t('welcome.description') })] }), _jsx(motion.div, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { duration: 0.6, delay: 0.3 }, className: "mb-8", children: _jsx(SpeechBubble, { tone: "sky", arrow: "bottom", className: "max-w-md mx-auto", children: _jsx("p", { className: "text-lg font-medium", children: locale === 'pirate'
                                ? '"Ahoy there, matey! I\'m Captain Luna, your guide to understanding emotions. Ready to set sail on this grand adventure?"'
                                : '"Ahoy there! I\'m Luna, your guide to understanding emotions. Ready to become a mood detective?"' }) }) }), _jsxs(motion.div, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { duration: 0.6, delay: 0.4 }, className: "mb-8", children: [_jsx("p", { className: "text-gray-600 mb-4", children: "Meet your friends:" }), _jsxs("div", { className: "flex justify-center space-x-4 text-3xl", children: [_jsx("span", { role: "img", "aria-label": "Tom", children: characterEmojis.tom }), _jsx("span", { role: "img", "aria-label": "Maya", children: characterEmojis.maya }), _jsx("span", { role: "img", "aria-label": "Rex", children: characterEmojis.rex })] })] }), _jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: 0.6 }, children: _jsx(Link, { to: "/characters", children: _jsx(Button, { variant: "sky", size: "lg", className: "transform hover:scale-105 transition-transform duration-200", children: t('welcome.startButton') }) }) }), _jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { duration: 0.6, delay: 0.8 }, className: "mt-8 text-sm text-gray-500", children: _jsx("p", { children: "Press Enter or Space to start your adventure!" }) }), _jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { duration: 0.6, delay: 1.0 }, className: "mt-6", children: _jsx(Card, { tone: "neutral", padding: "sm", className: "inline-block", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Language:" }), _jsx(Button, { variant: locale === 'en' ? 'sky' : 'ghost', size: "sm", onClick: () => setLocale('en'), className: "text-xs", children: "English" }), _jsx(Button, { variant: locale === 'pirate' ? 'banana' : 'ghost', size: "sm", onClick: () => setLocale('pirate'), className: "text-xs", children: "Pirate" })] }) }) })] }) }));
}
